server:
  port: 8082
spring:
  datasource:
    url: jdbc:h2:mem:db_categoria
    driverClassName: org.h2.Driver
    username: sa
    password: password
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true